
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BLL.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Cliente
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Cliente()
    {

        this.Cobro = new HashSet<Cobro>();

        this.Reserva = new HashSet<Reserva>();

        this.Venta = new HashSet<Venta>();

    }


    public int ID_CLIENTE { get; set; }

    public System.DateTime FECHA_ALTA { get; set; }

    public int COD_ESTADO { get; set; }

    public int TIPO_DOCUMENTO { get; set; }

    public int NRO_DOCUMENTO { get; set; }

    public string APELLIDO { get; set; }

    public string NOMBRE { get; set; }

    public string ALIAS { get; set; }

    public string TELEFONO_MOVIL { get; set; }

    public string TELEFONO_FIJO { get; set; }

    public string EMAIL { get; set; }

    public string CALLE { get; set; }

    public Nullable<int> NUMERO { get; set; }

    public string PISO { get; set; }

    public string DEPARTAMENTO { get; set; }

    public string BARRIO { get; set; }

    public string CODIGO_POSTAL { get; set; }

    public string PROVINCIA { get; set; }

    public string LOCALIDAD { get; set; }

    public string DIRECCION_MAPS { get; set; }

    public Nullable<System.DateTime> FECHA_BAJA { get; set; }



    public virtual TipoDocumento TipoDocumento { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Cobro> Cobro { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Reserva> Reserva { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Venta> Venta { get; set; }

}

}
