//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColeccionEntrega
    {
        public decimal ID_ENTREGA { get; set; }
        public decimal COD_COLECCION { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> NRO_ENTREGA { get; set; }
        public double PRECIO { get; set; }
    
        public virtual Coleccion Coleccion { get; set; }
    }
}
