
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BLL.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class DetalleVenta
{

    public int ID_DETALLE_VENTA { get; set; }

    public int COD_VENTA { get; set; }

    public int COD_PRODUCTO_EDICION { get; set; }

    public double PRECIO_UNIDAD { get; set; }

    public int CANTIDAD { get; set; }

    public double SUBTOTAL { get; set; }



    public virtual Venta Venta { get; set; }

    public virtual ProductoEdicion ProductoEdicion { get; set; }

}

}
