
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BLL.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class DetalleIngresoProducto
{

    public int ID_DETALLE_INGRESO_PRODUCTO { get; set; }

    public int COD_INGRESO_PRODUCTO { get; set; }

    public int CANTIDAD_UNIDADES { get; set; }

    public Nullable<System.DateTime> FECHA_DEVOLUCION { get; set; }

    public int COD_ESTADO { get; set; }

    public int COD_PRODUCTO { get; set; }

    public Nullable<int> COD_PRODUCTO_EDICION { get; set; }



    public virtual Estado Estado { get; set; }

    public virtual IngresoProducto IngresoProducto { get; set; }

    public virtual Producto Producto { get; set; }

    public virtual Producto_Edicion Producto_Edicion { get; set; }

}

}
