
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BLL.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class DetalleCobro
{

    public int ID_DETALLE_COBRO { get; set; }

    public int COD_COBRO { get; set; }

    public int COD_VENTA { get; set; }

    public double SUBTOTAL { get; set; }



    public virtual Cobro Cobro { get; set; }

    public virtual Venta Venta { get; set; }

}

}
