
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BLL.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class DiarioDiaSemana
{

    public int ID_DIARIO_DIA_SEMANA { get; set; }

    public int COD_DIARIO { get; set; }

    public int ID_DIA_SEMANA { get; set; }

    public Nullable<double> PRECIO { get; set; }



    public virtual Diario Diario { get; set; }

    public virtual DiaSemana DiaSemana { get; set; }

}

}
