
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BLL.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Libro
{

    public int ID_LIBRO { get; set; }

    public int COD_PRODUCTO { get; set; }

    public string EDITORIAL { get; set; }

    public string AUTOR { get; set; }

    public Nullable<int> ANIO { get; set; }

    public double PRECIO { get; set; }



    public virtual Producto Producto { get; set; }

}

}
