
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BLL.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Localidad
{

    public int ID_LOCALIDAD { get; set; }

    public string NOMBRE { get; set; }

    public int ID_PROVINCIA { get; set; }



    public virtual Provincia Provincia { get; set; }

}

}
