
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BLL.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Mensaje
{

    public int ID_MENSAJE { get; set; }

    public Nullable<int> COD_CLIENTE { get; set; }

    public string DESCRIPCION { get; set; }

    public string TIPO_MENSAJE { get; set; }

    public Nullable<bool> MENSAJE_VISTO { get; set; }

    public System.DateTime FECHA_REGISTRO_MENSAJE { get; set; }

    public Nullable<System.DateTime> FECHA_MODIFICACION_MENSAJE { get; set; }



    public virtual Cliente Cliente { get; set; }

}

}
