
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BLL.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Producto
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Producto()
    {

        this.Coleccions = new HashSet<Coleccion>();

        this.Diarios = new HashSet<Diario>();

        this.Libroes = new HashSet<Libro>();

        this.Peliculas = new HashSet<Pelicula>();

        this.Suplementoes = new HashSet<Suplemento>();

        this.Revistas = new HashSet<Revista>();

    }


    public int ID_PRODUCTO { get; set; }

    public System.DateTime FECHA_ALTA { get; set; }

    public string NOMBRE { get; set; }

    public string DESCRIPCION { get; set; }

    public int COD_ESTADO { get; set; }

    public int COD_GENERO { get; set; }

    public int COD_PROVEEDOR { get; set; }

    public Nullable<System.DateTime> FECHA_BAJA { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Coleccion> Coleccions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Diario> Diarios { get; set; }

    public virtual EstadoProducto EstadoProducto { get; set; }

    public virtual Genero Genero { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Libro> Libroes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Pelicula> Peliculas { get; set; }

    public virtual Proveedor Proveedor { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Suplemento> Suplementoes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Revista> Revistas { get; set; }

}

}
