
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BLL.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Producto
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Producto()
    {

        this.Coleccion = new HashSet<Coleccion>();

        this.DetalleIngresoProducto = new HashSet<DetalleIngresoProducto>();

        this.Diario = new HashSet<Diario>();

        this.Libro = new HashSet<Libro>();

        this.Pelicula = new HashSet<Pelicula>();

        this.Producto_Edicion = new HashSet<Producto_Edicion>();

        this.Revista = new HashSet<Revista>();

        this.Suplemento = new HashSet<Suplemento>();

    }


    public int ID_PRODUCTO { get; set; }

    public System.DateTime FECHA_ALTA { get; set; }

    public string NOMBRE { get; set; }

    public string DESCRIPCION { get; set; }

    public int COD_ESTADO { get; set; }

    public int COD_GENERO { get; set; }

    public int COD_PROVEEDOR { get; set; }

    public int COD_TIPO_PRODUCTO { get; set; }

    public Nullable<System.DateTime> FECHA_BAJA { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Coleccion> Coleccion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DetalleIngresoProducto> DetalleIngresoProducto { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Diario> Diario { get; set; }

    public virtual Estado Estado { get; set; }

    public virtual Genero Genero { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Libro> Libro { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Pelicula> Pelicula { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Producto_Edicion> Producto_Edicion { get; set; }

    public virtual Proveedor Proveedor { get; set; }

    public virtual TipoProducto TipoProducto { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Revista> Revista { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Suplemento> Suplemento { get; set; }

}

}
