
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BLL.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Reparto
{

    public int ID_REPARTO { get; set; }

    public int COD_CLIENTE { get; set; }

    public int COD_EDICION { get; set; }

    public string CLIENTE { get; set; }

    public string ORIGEN { get; set; }

    public string DESTINO { get; set; }

    public string EDICION { get; set; }

    public string PRODUCTO { get; set; }

    public int CANTIDAD { get; set; }

}

}
