//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RevistaEdicion
    {
        public decimal ID_EDICION { get; set; }
        public decimal COR_REVISTA { get; set; }
        public decimal NUMERO { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual Revista Revista { get; set; }
    }
}
