//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuplementoEdicion
    {
        public decimal ID_EDICION { get; set; }
        public decimal COD_SUPLEMENTO { get; set; }
        public Nullable<decimal> NUMERO { get; set; }
        public System.DateTime FECHA { get; set; }
        public double PRECIO { get; set; }
    
        public virtual Suplemento Suplemento { get; set; }
    }
}
