
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BLL.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Usuario
{

    public int ID_USUARIO { get; set; }

    public string NOMBRE_USUARIO { get; set; }

    public string NOMBRE { get; set; }

    public string APELLIDO { get; set; }

    public string CONTRASENIA { get; set; }

    public byte[] AVATAR { get; set; }

    public Nullable<System.DateTime> FECHA_BAJA { get; set; }

    public int ID_ROL { get; set; }



    public virtual Rol Rol { get; set; }

}

}
