
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BLL.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Usuario
{

    public int idUsuario { get; set; }

    public string NombreUsuario { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Contrasenia { get; set; }

    public int IdUsuarioTipo { get; set; }



    public virtual UsuarioTipo UsuarioTipo { get; set; }

}

}
